---

name: deeplabv3p

gops: [178.138]

shapes:
  - [1, 3, 640, 320]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/deeplabv3p.onnx
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [$(shape_param)]
    --mean 0.0,0.0,0.0
    --scale 0.0039216,0.0039216,0.0039216
    --pixel_format rgb
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

BM1684X:
  deploy:
    - model_deploy.py  --mlir $(workdir)/transformed.mlir
        --quantize F32
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_bm1684x_f32.bmodel
