---

name: vit-large-patch16-384
gops: 383.4 

time: true

model: $(home)/vit_L_16.onnx
input_shapes: "[1,3,384,384]"
batch_sizes: [1]

int8_model: $(workdir)/$(name)_bmneto_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmneto.int8umodel

BM1684X:
  fp_loops:
    - build_env: [ ]
      fp_outdir_template: "{}b.fp32.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_LAYER_DTYPE_MODE=auto
      fp_outdir_template: "{}b.fp16.compilation"
      prec: FP16

  fp_batch_sizes: $(batch_sizes)
  fp_compile_options:
    python3 -m bmneto
      --model $(model)
      --shapes $(input_shapes)
      --net_name $(name)
      --target $(target)
      --enable_profile true
      --cmp false

  time_only_cali:
    python3 -m ufw.cali.cali_model
      --model $(model)
      --input_shapes $(input_shapes)
      --net_name $(name)
      --target $(target)
      --cali_iteration 1
      --test_iterations 1
      --debug_cmd "not_call_bmnetu;not_suspend;use_fake_data_to_test"

  bmnetu_batch_sizes: $(batch_sizes)
  bmnetu_options:
    --model $(int8_model)
    --weight $(int8_weight)
    --target $(target)
    --enable_profile True
