---

name: efficientnetv2
gops: [5.9]
shapes:
  - [1, 3, 288, 288]

model: $(home)/efficientnetv2.onnx

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(model)
    --input_shapes [$(shape_param)]
    --mean 103.53,116.28,123.675
    --scale 0.0174291938,0.0175070028,0.0171247538
    --pixel_format rgb
    --test_input $(root)/dataset/samples/dog.jpg
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/$(name).mlir

mlir_calibration:
  run_calibration.py $(workdir)/$(name).mlir
    --dataset $(imagenet2012_mlir_cali_set)
    --input_num 200
    -o $(home)/$(name)_cali_table

BM1684X:
  deploy:
    - model_deploy.py --mlir $(workdir)/$(name).mlir
        --quantize F32
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_bm1684x_f32.bmodel
    - model_deploy.py --mlir $(workdir)/$(name).mlir
        --quantize F16
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_bm1684x_f16.bmodel
    - model_deploy.py --mlir $(workdir)/$(name).mlir
        --quantize INT8
        --calibration_table $(home)/$(name)_cali_table
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.95,0.70
        --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel

  dataset:
    image_path: $(imagenet2012_val_set)
    image_label: $(imagenet2012_caffe_val_ground_truth)
    mean: [123.675, 116.28, 103.53]
    scale: [0.0171247538, 0.0175070028, 0.0174291938]
    size: 288
    trans: True
    bgr2rgb: True

  harness:
    type: efficientnetv2
    args:
      - name: FP32
        bmodel: $(workdir)/$(name)_bm1684x_f32.bmodel
      - name: INT8
        bmodel: $(workdir)/$(name)_bm1684x_int8_sym.bmodel
