---

name: yolov5x
gops: [16.588894000]
shapes:
  - [1, 3, 640, 640]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/yolov5x.onnx
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [$(shape_param)]
    --keep_aspect_ratio
    --mean 0.0,0.0,0.0
    --scale 0.0039216,0.0039216,0.0039216
    --pixel_format rgb
    --output_names 701,849,997
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

mlir_calibration:
  run_calibration.py $(workdir)/transformed.mlir
    --dataset $(coco2017_mlir_cali_set)
    --input_num 100
    -o $(workdir)/$(name).xcali_table

dataset:
  imagedir: $(coco2017_val_set)
  anno: $(coco2017_anno)/instances_val2017.json

deploy:
  - model_deploy.py  --mlir $(workdir)/transformed.mlir
      --quantize F32
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.99,0.99
      --model $(workdir)/$(name)_$(target)_f32.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --calibration_table $(workdir)/$(name).xcali_table
      --chip $(target)
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.95,0.68
      --model $(workdir)/$(name)_$(target)_int8_sym.bmodel

BM1684:
  harness:
    type: yolo
    args:
      - name: FP32
        bmodel: $(workdir)/$(name)_$(target)_f32.bmodel
      - name: INT8
        bmodel: $(workdir)/$(name)_$(target)_int8_sym.bmodel

BM1684X:
  +deploy:
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize INT8
        --asymmetric
        --calibration_table $(workdir)/$(name).xcali_table
        --chip $(target)
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.90,0.54
        --model $(workdir)/$(name)_$(target)_int8_asym.bmodel

  harness:
    type: yolo
    args:
      - name: FP32
        bmodel: $(workdir)/$(name)_$(target)_f32.bmodel
      - name: INT8
        bmodel: $(workdir)/$(name)_$(target)_int8_sym.bmodel
      - name: INT8
        bmodel: $(workdir)/$(name)_$(target)_int8_asym.bmodel
