---

name: Test MLIR
on:
  push:
  pull_request:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC time 22:30
    # Wednesday and Saturday
    - cron: '30 22 * * 3,6'
  workflow_dispatch:
    inputs:
      cases:
        description: 'Cases to run'
        default: '--full'
        required: false
        type: string

concurrency:
  group: |
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_build:
    if: github.repository == 'sophgo/model-zoo'
    name: MLIR Build
    runs-on: build
    timeout-minutes: 10080
    outputs:
      MLIR_MODEL_TAR: ${{ steps.test.outputs.MLIR_MODEL_TAR }}

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false
          lfs: false

      - name: LFS Pull
        run: git lfs pull --exclude '' --include '*'

      - name: Set Optional Env
        if: "${{ github.event_name == 'schedule' || \
                 contains( \
                   github.event.pull_request.labels.*.name, \
                   'full_regression' \
                 ) }}"
        run: |
          echo "FULL_TEST=true" >> $GITHUB_ENV

      - name: Test
        run: ".github/workflows/test.sh -m 'build and mlir' ${{ inputs.cases }}"
        id: test

      - name: Cleanup
        if: ${{ cancelled() || failure() }}
        run: .github/workflows/cleanup.sh

  test_runtime_BM1684X:
    if: github.repository == 'sophgo/model-zoo'
    name: BM1684X MLIR Runtime
    runs-on: [runtime, BM1684X]
    needs: test_build

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false
          lfs: false

      - name: LFS Pull
        run: |
          git lfs pull --exclude '' --include 'dataset/ILSVRC2012/*'

      - name: Set Optional Env
        if: "${{ github.event_name == 'schedule' || \
                 contains( \
                   github.event.pull_request.labels.*.name, \
                   'full_regression' \
                 ) }}"
        run: |
          echo "FULL_TEST=true" >> $GITHUB_ENV

      - name: Test
        run: |
          .github/workflows/test.sh -m 'runtime and mlir' -t BM1684X \
              ${{ inputs.cases }}
        env:
          MLIR_MODEL_TAR: ${{ needs.test_build.outputs.MLIR_MODEL_TAR }}

      - name: Cleanup
        if: ${{ cancelled() || failure() }}
        run: .github/workflows/cleanup.sh

  test_runtime_BM1684:
    if: github.repository == 'sophgo/model-zoo'
    name: BM1684 MLIR Runtime
    runs-on: [runtime, BM1684]
    needs: test_build

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false
          lfs: false

      - name: Set Optional Env
        if: "${{ github.event_name == 'schedule' || \
                 contains( \
                   github.event.pull_request.labels.*.name, \
                   'full_regression' \
                 ) }}"
        run: |
          echo "FULL_TEST=true" >> $GITHUB_ENV

      - name: Test
        run: |
          .github/workflows/test.sh -m 'runtime and mlir' -t BM1684 \
              ${{ inputs.cases }}
        env:
          MLIR_MODEL_TAR: ${{ needs.test_build.outputs.MLIR_MODEL_TAR }}

      - name: Cleanup
        if: ${{ cancelled() || failure() }}
        run: .github/workflows/cleanup.sh
